// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAeD06X_Vyq1bIHX9DrgKsFaPo-Vfyf4o',
    appId: '1:417578012994:web:b29846dac71e97084578db',
    messagingSenderId: '417578012994',
    projectId: 'netflixclone-e1f7e',
    authDomain: 'netflixclone-e1f7e.firebaseapp.com',
    storageBucket: 'netflixclone-e1f7e.appspot.com',
    measurementId: 'G-ZLRG2LY1F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuSYquQZyJj-viBRMbcf0rQpjC8CfyvY4',
    appId: '1:417578012994:android:8c18aa856f5c0e6c4578db',
    messagingSenderId: '417578012994',
    projectId: 'netflixclone-e1f7e',
    storageBucket: 'netflixclone-e1f7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBIkVe2NqSnUzUhgWmAX3pe7-cramuyM',
    appId: '1:417578012994:ios:279f89dd6e6635e94578db',
    messagingSenderId: '417578012994',
    projectId: 'netflixclone-e1f7e',
    storageBucket: 'netflixclone-e1f7e.appspot.com',
    iosClientId: '417578012994-jo07gja4i2coggdlrk15sjqcj1bquhpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACBIkVe2NqSnUzUhgWmAX3pe7-cramuyM',
    appId: '1:417578012994:ios:279f89dd6e6635e94578db',
    messagingSenderId: '417578012994',
    projectId: 'netflixclone-e1f7e',
    storageBucket: 'netflixclone-e1f7e.appspot.com',
    iosClientId: '417578012994-jo07gja4i2coggdlrk15sjqcj1bquhpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );
}
